language: scala

scala:
  - 2.10.6
  - 2.11.11
  - 2.12.2
jdk: oraclejdk8

script:
- sbt ++${TRAVIS_SCALA_VERSION} coreJVM/test coreJS/test scalazJVM/test scalazJS/test experimentalJVM/test experimentalJS/test

matrix:
  include:
  - sudo: required
    dist: trusty
    scala: 2.11.11
    before_install:
    - curl https://raw.githubusercontent.com/scala-native/scala-native/v0.3.0/bin/travis_setup.sh | bash -x
    script:
    - sbt ++${TRAVIS_SCALA_VERSION} scalazNative/test
